# Generated by Django 5.2.3 on 2025-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
