# Generated by Django 5.2.3 on 2025-06-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0002_event_image_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
